### ISSUE TITLE
[BUG] Markdown Lint Configuration

### ISSUE THREAD

**Issue by eduardomr** [houdiniproject/houdini#1560]
## Description
There is a need to lint all of the markdown files in the repository and eliminate all of the exclusions currently in place. However, it is not clear where the markdown linting exclusions are set.

## Expected Behavior
All markdown files in the repository should be linted, including those that are currently excluded from the linting process.

## Actual Behavior
Markdown files in the repository are being linted, but there are exclusions in place that prevent some files from being checked. It is unclear where these exclusions are defined or how to modify them.

**Comment by BenSturmfels** [comment]
Hi @eduardomr, is the problem that there an error in the Markdown somewhere you feel should have been detected? Can you provide an example?

In `.github/workflows/pr.yml` you'll see the configuration for the GitHub action that runs `yarn markdownlint`, which ultimately translates to:

`npx markdownlint-cli **/*.md --ignore node_modules`

There's also a config file `.markdownlint.jsonc`. Not sure that markdownlint would find a `.jsonc` file - I haven't tested whether this config is actually taking effect.

**Comment by eduardomr** [comment]
Hi @BenSturmfels, we believe that the README is not being checked by the markdown lint, however we cannot find where this setting was made.

**Comment by BenSturmfels** [comment]
@eduardomr @wwahammy it looks like the culprit is that `**/*.md` isn't quoted in the command and is being treated as a shell glob. I would recommend either:

`npx markdownlint-cli '**/*.md' --ignore node_modules`

or even better - you only ever want to check the files that are in the repository:

`git ls-files '*.md' | xargs npx markdownlint-cli`

Be aware that this second option will flag Markdown errors in the vendored `gems` directory, which is probably a good thing, but a little noisy to begin with.
