### ISSUE TITLE
v1 Bcrypt invalid hash on user creation.

### ISSUE THREAD

**Issue by tony-gutierrez** [houdiniproject/houdini#527]
## Description
```
Completed 500 Internal Server Error in 86.74ms (Views: 84.92ms | DB: 1.82ms)


BCrypt::Errors::InvalidHash (invalid hash):
  app/api/houdini/v1/nonprofit.rb:84:in `new'
  app/api/houdini/v1/nonprofit.rb:84:in `block (2 levels) in <class:Nonprofit>'
  app/api/houdini/v1/nonprofit.rb:60:in `block in <class:Nonprofit>'
  config/initializers/quiet_assets.rb:8:in `call_with_quiet_assets'

```

## Expected Behavior
User gets saved

## Actual Behavior
Error above causes 500 response 

## Possible Fix
Updated bcrypt gem to 3.1.16, fixed.

## Steps to Reproduce

1. Unbuntu 20.4
2. Try onboarding
3.
4.

## Your Environment

* Ruby version: 2.3.7
* Server type and version: Unbuntu 20.4
* Operating System and version:
* Link to your project:

**Comment by tony-gutierrez** [comment]
Perhaps need to update the gem version in the repo?

**Comment by wwahammy** [comment]
@tony-gutierrez was it an upgrade of the bcrypt Gem itself to '3.1.16' that fixed this?

**Comment by wwahammy** [comment]
Also, thanks for the report and for debugging it!

**Comment by wwahammy** [comment]
Nah, you're just fine at rails. 

The proper way to correct this bug is adding the following line to `Gemfile`:

`gem 'bcrypt', '~> 3.1.16'`

and then run `bundle update bcrypt`. That would make sure that there are no package versions conflicts and updates `Gemfile.lock` for you.

Also, make sure you revert your change in `Gemfile.lock` first.

I hope that works!
