### ISSUE TITLE
[FEATURE] Startup docs....

### ISSUE THREAD

**Issue by iRunner** [houdiniproject/houdini#554]
I have been trying to test this package and it's been super frustrating just to get started... hidden required environment variables... non-profit doesn't exist, no way of knowing if the setup was done correctly or if it's a bug... 

Friendlier startup docs would be helpful 

I can submit a PR for setup documentation ~ It would help if I could get a software walkthrough though

<img width="1893" alt="Screen Shot 2021-03-27 at 11 04 24 PM" src="https://user-images.githubusercontent.com/1361295/112741421-b532e080-8f53-11eb-9102-f1a5987508b6.png">

**Comment by wwahammy** [comment]
Hey @iRunner! Thanks for being involved. We totally agree it's too hard to get setup; because of commitment from folks like you, it's actually getting better! We're all on the same team here so we appreciate you chipping in.

It looks like the javascript assets aren't being generated. Did this happening when you ran `bin/rails server`? If so, did you see any errors in the terminal?

**Comment by clarissalimab** [comment]
It once happened to me not to set up my environment correctly because I assumed it was a regular Rails project and I tried configuring without following all the steps. Once I noticed there are a few different steps I restarted the process, and it was pretty straightforward to me.

I had the same issue as yours because I didn't run `bin/setup` at first. This script also creates the `.env` file!

**Comment by GuilhermeBraz** [comment]
Hey @wwahammy, our group (@GuilhermeBraz, @jpcirqueira, @LucasA27) is thinking on taking on this issue. We are thinking on upgrading the readme on certain topics, such as adding a step-by-step tutorial for adding the stripe keys to the .env file and to make certain steps easier to follow.

**Comment by wwahammy** [comment]
I think that's a good idea!

Also, in regards to simplifying setup of private keys, like stripe keys, please look into migrating secrets to using Rails credentials as described at: https://guides.rubyonrails.org/v6.1/security.html#environmental-security. I haven't looked too much into this but it's really a better way to handle this because then you only need a single key in the .env file.
