### ISSUE TITLE
[BUG] Document translation process

### ISSUE THREAD

**Issue by wwahammy** [houdiniproject/houdini#840]
Currently, our translation process uses a [Transfex project](https://www.transifex.com/houdini-project/houdini/dashboard/) for managing it. I think that, in principle, is perfectly fine. That said, we basically don't have a translation process or formal guidelines on how translations should work, where sources should be added, etc.

I generally think it should follow the following design:

* Strings get added to the English translations in `config/locales`
  * If a new locale file is added, it needs to be added to Transifex as a new resource
* When new English strings are added, they should be synced to Transifex.
* When new translations are created, a PR should be created with the change to merge in the change.

Some open questions:
* When is a string added? Once merged into main?
* What's the mechanism for updating those strings? If manual, what's the steps to make sure nothing falls through the cracks?
* How do we add new people to the translation process?
* How are PRs created for updates to translations? If manual, what's the steps to make sure nothing falls through the cracks?
* How do people decide when to create a new locale file? Generally I think it should be a different locale file for each significant UI component.

**Comment by clarissalimab** [comment]
About the open questions:

> When is a string added? Once merged into main?
> What's the mechanism for updating those strings? If manual, what's the steps to make sure nothing falls through the cracks?
> How are PRs created for updates to translations? If manual, what's the steps to make sure nothing falls through the cracks?

I think the order doesn't matter, especially because of the choice of editing on Transifex or directly on the translation files, what we need to make sure is that either way the translator chooses, they or we upload the changes on the repository or on Transifex. I described the steps in the guide.

> How do we add new people to the translation process?

They can ask to join the project on Transifex, but I didn't find it very effective because if someone has translation access to the project, they can edit existing translations easily, so I think it would be better if we asked the contributor to fill in a issue with some information and we send an invite. I'm just not sure how we make sure that we can trust this person.

> How do people decide when to create a new locale file? Generally I think it should be a different locale file for each significant UI component.

I agree.

***

I tried to make the translation process as less technical as possible, so that external translators can contribute easier without the git friction, but they can help us updating the repository with their translations if they feel comfortable with git. I just don't know how we can make it possible that translators require reviews on their translations, or how do they let us know that there are translations that need to be synced with our repo without the need of them sending the PR.

Summarizing:

* Is it a good idea to ask the translators to fill an issue to join the Transifex project? What do we need to ask them?
* How are we going to handle reviews on Transifex?
* Additionally, do you think I should add more details on how to edit translations?

***
> Draft 1

# Translation process

This document describes the workflows to be able to do the following translating tasks:

* Making a page or component translatable;
* Translating a page to some language other than English;
  * Using Transifex;
  * Manually adding translations.
* Adding new strings;
* Removing strings;
* Modifying a translation:
  * Changing its key;
  * Changing its string;
  * Removing a translation.

We use a [Transifex project](https://www.transifex.com/houdini-project/houdini/dashboard/) to work on our translations.

Our source language is English.

## Getting started

If you want to help Houdini with translations, you can do it by using our [Transifex project](https://www.transifex.com/houdini-project/houdini/dashboard/) to add your translations (see [Translating strings to some language other than English > Using Transifex](#using-transifex)). You can request translator access to it by filling an issue using [this link]() *-- there should be a link here for opening an issue following the template*.

Otherwise, you can create your fork of the project and submit your contributions following the [Translating strings to some language other than English > Manually adding translations](#manually-adding-translations) guide.

If a page or component does not have translations yet, you're going to need to follow the [Making a component translatable](#making-a-component-translatable) guide to create the source translation file and adding support to i18n to the component before adding translations to another language.

Every change that we make on translations should be reflected on both Houdini's repository and Transifex. Here's a summary of the workflow:

![Translation Process drawio](https://user-images.githubusercontent.com/15739610/142492823-1aad63c6-ed10-4550-8ce4-d70659dd097c.png)

## Translating strings to some language other than English

### Using Transifex

1. From [Transifex's dashboard](https://www.transifex.com/houdini-project/houdini/dashboard/), click on the `Translate` button, choose the language and the source from which you are translating.

2. Translate the strings to the desired language.

> Note: If the language still doesn't exist on Transifex, you can request that a language gets added by going to [Transifex's dashboard](https://www.transifex.com/houdini-project/houdini/dashboard/) and clicking "Request a language".

3. When you're done, go back to the dashboard and click `View resources` on the corresponding language that you just translated to.

4. Ask a maintainer to review your translations (?).

#### (Optional) Additional steps: sending your translations to Houdini's repository

If you are familiar to Git and sending contributions to open source projects, you can help us by submitting your translations directly to Houdini's repository.

5. Click on the file you have translated, and then download it by clicking on `Download only reviewed translations`.

6. Place the on Houdini's project, under the `config/locales` folder, and name it with the translation you did. For example, if you translated `roles.new.en.yml` from English to Brazilian Portuguese, the file name should be `roles.new.pt_BR.yml`.

7. Commit your changes and submit a pull request.

8. If the reviewer request changes on the translations, you can do the changes on Transifex by editing the translations and repeating the steps from 3 to 5, commiting the changes and pushing them. You can edit the file directly instead of doing the changes on Transifex and downloading them again. If you do so, don't forget to update the changes on Transifex.

### Manually adding translations

> Note: You can only do this way if you are familiar to Git and sending contributions to open source projects. If you are not, please, send your contributions following the [Using Transifex](#Using-Transifex) guide.

1. Find the translation file that you want to translate under `config/locales` folder.

2. If the translation file already exists, move to step 4. If not, make a copy of that file and change the name of it to reflect the language that you are translating to.

If you are translating from English to Brazilian Portuguese, you should replace `en` in the file name with `pt_BR`, for example.

3. Open the file and rename the source language key for the new translation key.

For example, if you are translating from English to Brazilian Portuguese, this is how it would look like:

Original

```yml
en:
  roles:
    new:
    ...
```

New translation

```yml
pt_BR:
  roles:
    new:
    ...
```

4. Translate the strings:

Original

```yml
en:
  roles:
    new:
      invite_a_new_user: Invite a New User
      nonprofit_admin: Nonprofit Admin
      ...
```

New translation

```yml
pt_BR:
  roles:
    new:
      invite_a_new_user: Convide um Novo Usuário
      nonprofit_admin: Administrador da Organização
      ...
```

5. Commit your changes and submit a pull request.

#### (Optional) Additional steps: uploading your translations to Transifex

If you have access to our Transifex project, you can help us by uploading your new translations to Transifex.

6. Once your changes are approved and merged, go to our [Transifex project](https://www.transifex.com/houdini-project/houdini/dashboard/) and select the language to which you just created the translation and clicking `View resources`.

7. Choose the source file name that you translated from the list and click `Upload file` and upload the translation file you just created.

## Making a component translatable

Some components are still not translatable using i18n, as they are disposed in plain text on the view files.

To enable translations on a page, we need to follow the steps below:

1. Identify the name for the strings that will be translated.

Every significant component needs to have its own translation name. For example, [app/views/roles/_new_modal.html.erb](app/views/roles/_new_modal.html.erb)'s translations were named as `roles.new`, as they refer to creating a new role.

The name of the file for the translations should follow the strings names, followed by the language to which the component is being translated to. Since making a component translatable requires that we create a file with strings in English, the file name should end with `.en.yml`.


Example:

```yml
en:
  roles:
    new:
      invite_a_new_user: Invite a New User
      nonprofit_admin: Nonprofit Admin
      ...
```

The file name for the example above would be `roles.new.en.yml`, placed at `config/locale`.

We can also have translations for strings that are shared in multiple components. For example, [config/locales/ui.en.yml](config/locales/ui.en.yml) holds UI strings that can be shared between multiple components, such as common button labels or links.

2. Find every string that is going to be translated, create a key for it and place it into your translation file.

It's important to give it a well detailed name, so that when someone is reading the code on the component they automatically understand what that string is without having to look at the translation file.

For example, the text `Full permissions, including bank payouts` on [roles.new.en.yml](config/locales/roles.new.en.yml), as big as it is, has the key `full_permissions_including_bank_payouts`.

3. Replace the strings from the components with their corresponding keys.

Example: Replace the "Full permissions, including bank payouts" text for `t('roles.new.full_permissions_including_bank_payouts')`.

4. Commit the changes and open a pull request to Houdini/main.

5. After the pull request is merged, **if you created one or more translation files**, create a new resource on [Houdini's Transifex project](https://www.transifex.com/houdini-project/houdini/content/) for each translation file created, naming it after the name of the translation file.

6. Enable the auto update on your source files by clicking on the `Auto update resources` and add the URL for the raw file on GitHub for the translation file on main branch.

## Modifying translations

* If we are changing the key for a string, we need to make sure to update it on every translation file and to replace every original reference for its new key;
* If we are changing the translation string, then we just need to normally edit the strings and submit the changes to Transifex and to Houdini's repository;
* If we are adding new strings, we need to add them to the source translation files (in English), and proceed to translate them to the desired languages;
* If we are removing a string that is not being used anymore or is duplicated, we need to make sure that every existing reference of it is removed or replaced to a new one before removing. If so, then we need to remove them from every translation file.

Whenever we do any change on Transifex, we need to download the newest version of the translation files and submit a pull request for taking effect on Houdini. In the same way, whenever we do any change manually on the translation files, we need to upload the newest version to Transifex once the changes are approved.

**Comment by wwahammy** [comment]
I think this is a good starting point! A few things to consider:

* How do we keep Transifex and Github in sync? There are some actions and apps for Transifex that might improve this but even if we don't have those, we should document the process for keeping them in sync.
* It should be clear that the translation mechanism you described is only for Erb and Ruby files. It's a different process for Javascript,
* Not sure on the process for adding new translators. The free tier for Transifex that we qualify for doesn't really have a great mechanism for handling this.

**Comment by wwahammy** [comment]
A few other thoughts!

* On translators, perhaps we could require references of some sort? Not sure that's necessary but it's an idea. Then again, we should be careful about discouraging helpful contributions so maybe not?
* Is there any sort of heuristic people should use on naming new files and translation keys?

**Comment by wwahammy** [comment]
Oops on more:

* I can see advantages to not saying "you can do translations in either Transifex or in Github" but say "you must do translations in Transifex" just because there's less confusion as to which process should be used and simplifies syncing. Then again, that limits options. Do we think those options are more important than than simplification?

**Comment by clarissalimab** [comment]
> How do we keep Transifex and Github in sync? There are some actions and apps for Transifex that might improve this but even if we don't have those, we should document the process for keeping them in sync.

Good to know, I'm going to look into that! If I don't find anything to make it automatic, I'm going to document the manual process in more details.

> It should be clear that the translation mechanism you described is only for Erb and Ruby files. It's a different process for Javascript

I forgot about that, I'm going to add details for that.

> On translators, perhaps we could require references of some sort? Not sure that's necessary but it's an idea. Then again, we should be careful about discouraging helpful contributions so maybe not?

I think we can ask them if they already contributed to other FOSS projects and how, but if it's their first time contributing I don't know what else we can ask.

> Is there any sort of heuristic people should use on naming new files and translation keys?

I'm going to look into that.

> I can see advantages to not saying "you can do translations in either Transifex or in Github" but say "you must do translations in Transifex" just because there's less confusion as to which process should be used and simplifies syncing. Then again, that limits options. Do we think those options are more important than than simplification?

To me, simplification is more important, well thought!

**Comment by clarissalimab** [comment]
I didn't find any guides regarding naming translation files, I saw that some repositories have one file for each language, and I've seen in the past projects that would have separate folders for each language with the file name for the component, so `config/locales/roles.new.en.yml` would be `config/locales/en/roles.new.yml` instead, or, because English is our source language, it could be placed directly on `config/locales`. It would make sense because the name would follow the order of the keys that are accessed during the translation when we look at the yml file (`en.roles_new.<some_key`).

***
> Draft 2
# Translation process

This document describes the workflows to be able to do the following translating tasks:

* Translating strings using Transifex;
* Making a page or component translatable;
* Modifying a translation:
  * Changing keys;
  * Changing translation strings;
  * Adding new translation strings;
  * Removing translation strings.

We use a [Transifex project](https://www.transifex.com/houdini-project/houdini/dashboard/) to work on our translations.

Our source language is English.

## Getting started

If you want to help Houdini with translations, you can do it by using our [Transifex project](https://www.transifex.com/houdini-project/houdini/dashboard/) to add your translations (see [Translating strings to some language other than English > Using Transifex](#translating-strings-using-transifex)). You can request translator access to it by filling an issue using [this link](). *-- there should be a link here for opening an issue following the template*

If a page or component does not have translations yet, you're going to need to follow the [Making a component translatable](#making-a-component-translatable) guide to create the source translation file and adding support to i18n to the component before adding translations to another language.

## Translating strings using Transifex

Requirements:
* Have access to Houdini's Transifex project;
  * If not, you can get it by filling an issue using [this link](). *-- there should be a link here for opening an issue following the template* 
* The page, component or string you want to translate is translatable.
  * You can check that by looking for it on Transifex. If it's not, you can help us by making it translatable by following [this guide](#making-a-component-translatable).

1. From [Transifex's dashboard](https://www.transifex.com/houdini-project/houdini/dashboard/), click on the `Translate` button, choose the language and the source from which you are translating.

2. Translate the strings to the desired language.

> Note: If the language still doesn't exist on Transifex, you can request that a language gets added by going to [Transifex's dashboard](https://www.transifex.com/houdini-project/houdini/dashboard/) and clicking "Request a language".

The process of submitting the translations to Houdini's repository is automatic, but only if you translate 100% of the strings from a file.

## Making a component translatable

Some components are still not translatable using i18n, as they are disposed in plain text on the view files.

To enable translations on a page, we need to follow the steps below:

1. Identify the name for the strings that will be translated.

Every significant component needs to have its own translation name. For example, [app/views/roles/_new_modal.html.erb](app/views/roles/_new_modal.html.erb)'s translations were named as `roles.new`, as they refer to creating a new role.

The name of the file for the translations should follow the strings names, followed by the language to which the component is being translated to. Since making a component translatable requires that we create a file with strings in English, the file name should end with `.en.yml`.


Example:

```yml
en:
  roles:
    new:
      invite_a_new_user: Invite a New User
      nonprofit_admin: Nonprofit Admin
      ...
```

The file name for the example above would be `roles.new.en.yml`, placed at `config/locale`.

We can also have translations for strings that are shared in multiple components. For example, [config/locales/ui.en.yml](config/locales/ui.en.yml) holds UI strings that can be shared between multiple components, such as common button labels or links.

2. Find every string that is going to be translated, create a key for it and place it into your translation file.

It's important to give it a well detailed name, so that when someone is reading the code on the component they automatically understand what that string is without having to look at the translation file.

For example, the text `Full permissions, including bank payouts` on [roles.new.en.yml](config/locales/roles.new.en.yml), as big as it is, has the key `full_permissions_including_bank_payouts`.

3. Replace the strings from the components with their corresponding keys.

Examples:

* On .erb files, you should replace the "Full permissions, including bank payouts" text for `t('roles.new.full_permissions_including_bank_payouts')`;
* For `.tsx` files, you should import the `useIntl` hook from the `intl` component and import `formatMessage` from it. You should then create a constant with `formatMessage({ id: 'roles.new.full_permissions_including_bank_payouts' })` and replace the text by the name of the constant you created - you can look at how it's done on our [SignInComponent.tsx](https://github.com/houdiniproject/houdini/blob/a31e755f1bdf21c5c894018fe8ec3b26fcf6c896/app/javascript/components/users/SignInComponent.tsx#L77);
* For `.js` or `.es6` files, replace the text with `I18n.t('roles.new.full_permissions_including_bank_payouts')`.

4. Commit the changes and open a pull request to Houdini/main.

> Additional permissions on Transifex are needed to proceed with the next steps. If you have already opened the pull request and it has been approved, then you've done enough! :)

> The following steps are only required **if you created one or more translation files**.

5. After the pull request is merged, **if you created one or more translation files**, create a new resource on [Houdini's Transifex project](https://www.transifex.com/houdini-project/houdini/content/) for each translation file created, naming it after the name of the translation file.

6. Enable the auto update on your source files by clicking on the `Auto update resources` and add the URL for the raw file on GitHub for the translation file on main branch.

7. Go to the [integration settings, under the project settings](https://www.transifex.com/houdini-project/houdini/settings/integrations/).

8. Click on the three-dots icon on the GitHub integration and click `Edit Settings`.

9. Add a new filter type for that file. The example below shows how it would be done for the `roles.new.en.yml` file:

```yml
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: YML
    source_language: en
    source_file: config/locales/roles.new.en.yml
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: 'config/locales/roles.new.<lang>.yml'
```

10. Click `Update Settings`. Once you translate 100% of that file to another language, Transifex is going to create a pull request with your translation automatically.

## Modifying translations

* Changing keys is not recommended, as Transifex would consider it a completely new string. Still, we may need it sometimes, so a better approach would be to change them locally and push to the repository instead of doing it through Transifex.
  * Remember to update every reference of this key on the components to the new ones.
* Changing translation values can be done directly through Transifex, which will be updated automatically to the repository;
* Adding new strings requires an upload of the source file with the new string to Transifex or submitting a pull request with the new string that is going to be automatically updated on Transifex;
* Removing strings also requires that the process is done locally, updating the source file and sending a pull request to the repository. Removing the strings from the translations files is also needed.
  * Remember to make sure that every existing reference of it is removed or replaced to a new one before removing.

**Comment by wwahammy** [comment]
@clarissalimab could you evaluate [Crowdin.com](https://crowdin.com/project/houdiniproject) and see if you think working with it may make more sense? My quick opinion is that it is but I'm not sure. Once you give me your feedback, we can decide on whether to move to Crowdin and how to adjust this document for that.

**Comment by clarissalimab** [comment]
I really liked the translations suggestions, they are very helpful. I couldn't find is if it opens a pull request automatically with the changes and if it uses the same branch.

I was unsure about the process on Transifex because it's easy to just change a translation and it overwrites the existing one (there's a history, but I don't know, it would be better to have a simple version system). Do you think this workflow is better with Crowdin? What else do you think Crowdin is better at?

**Comment by wwahammy** [comment]
Not exactly sure how Crowdin works as it relates to PRs. Not sure how it sets up.

Crowdin feels cleaner and more mature for me. It has the ability to do reviews, add screenshots, and it has support for crowd sourcing translations by users submitting their own translations. It just seems better for an open source project.

**Comment by clarissalimab** [comment]
That's wonderful! I tried to sync it from the interface, but it seems it's not automatic, but they have this: https://support.crowdin.com/github-crowdin-action/, and we can tweak it to our use case. I think it's great!
